language: python
python:
  - "3.7"

services:
  - docker

before_install:
  - pip install docker-compose
  - docker-compose build
script:
  - docker-compose run api sh -c "python manage.py test && flake8"
