language: python
python:
  - "3.8"

services:
  - docker

before_install:
  - docker build -t nikitaproks/django-test -f ./api/Dockerfile ./api

script:
  - docker run -e CI=true nikitaproks/django-test python manage.py test && flake8
