version: "3"

services:
  api:
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
