# Generated by Django 3.1.4 on 2020-12-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredints',
            new_name='ingredients',
        ),
    ]
